AWSTemplateFormatVersion: "2010-09-09"
Description: Stack template for S# resources

Parameters:
  CodeDeployRoleArn: { Type: String }
  CodePipelineRoleArn: { Type: String }
  EventBridgeRoleArn: { Type: String }

Resources:
  # S3 bucket for storing artifacts
  PipelineArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "artifacts-taskify-app-bucket-8574"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  PipelineArtifactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PipelineArtifactBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref CodeDeployRoleArn
                - !Ref CodePipelineRoleArn
                - !Ref EventBridgeRoleArn
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:GetObjectVersion
              - s3:GetBucketVersioning
            Resource: 
              - !Sub arn:aws:s3:::${PipelineArtifactBucket}/*
              - !Sub arn:aws:s3:::${PipelineArtifactBucket}
          - Effect: Allow
            Principal:
              AWS:
                - !Ref CodeDeployRoleArn
                - !Ref CodePipelineRoleArn
                - !Ref EventBridgeRoleArn
            Action:
              - s3:ListBucket
            Resource: !Join ["", ["arn:aws:s3:::", !Ref PipelineArtifactBucket]]

Outputs:
  PipelineArtifactBucketName:
    Value: !Ref PipelineArtifactBucket
  PipelineArtifactBucketArn:
    Value: !GetAtt PipelineArtifactBucket.Arn
